INSERT INTO authors (name_korean, name_original) VALUES
  ('가오싱젠', NULL),
  ('강동훈', NULL),
  ('강세영', NULL),
  ('강준영', NULL),
  ('강지형', NULL),
  ('강하늘', NULL),
  ('강현주', NULL),
  ('게르하르트 하웁트만', 'Gerhart Hauptmann'),
  ('게오르그 뷔히너', NULL),
  ('게오르크 뷔히너', 'Georg Büchner'),
  ('게오르크 카이저', 'Georg Kaiser'),
  ('경민선', NULL),
  ('고동율', NULL),
  ('고연옥', NULL),
  ('고영범', NULL),
  ('고재귀', NULL),
  ('고찬하', NULL),
  ('고트홀트 레싱', 'Gotthold Ephraim Lessing'),
  ('고해성', NULL),
  ('관한경', 'Guan Hanqing'),
  ('구두리', NULL),
  ('구레이', NULL),
  ('구와바라 유코', NULL),
  ('구자혜', NULL),
  ('구지수', NULL),
  ('국민성', NULL),
  ('궈스싱', NULL),
  ('권미솔', NULL),
  ('그리고리 고린', 'Grigori Gorin'),
  ('극단 미인', NULL),
  ('극단 신세계', NULL),
  ('극단 실한', NULL),
  ('기국서', NULL),
  ('기군상', 'Ji Junxiang'),
  ('기시다 구니오', 'Kunio Kishida'),
  ('기시다 구시오', NULL),
  ('기타무라 소', 'So Kitamura'),
  ('기하라', NULL),
  ('김경주', NULL),
  ('김광림', NULL),
  ('김나연', NULL),
  ('김나영', NULL),
  ('김나정', NULL),
  ('김다솔', NULL),
  ('김다운', NULL),
  ('김도영', NULL),
  ('김동수', NULL),
  ('김록원', NULL),
  ('김리리', NULL),
  ('김마딘', NULL),
  ('김명곤', NULL),
  ('김명화', NULL),
  ('김묘진', NULL),
  ('김물', NULL),
  ('김미리', NULL),
  ('김미정', NULL),
  ('김민기', NULL),
  ('김민정', NULL),
  ('김봄', NULL),
  ('김상수', NULL),
  ('김상열', NULL),
  ('김서현', NULL),
  ('김선희', NULL),
  ('김성환', NULL),
  ('김세한', NULL),
  ('김수연', NULL),
  ('김수웅', NULL),
  ('김수정', NULL),
  ('김수희', NULL),
  ('김숙종', NULL),
  ('김슬기', NULL),
  ('김승철', NULL),
  ('김연옥', NULL),
  ('김연재', NULL),
  ('김영수', NULL),
  ('김옥미', NULL),
  ('김우진', NULL),
  ('김유경', NULL),
  ('김윤실', NULL),
  ('김윤영', NULL),
  ('김은성', NULL),
  ('김의경', NULL),
  ('김인규', NULL),
  ('김재엽', NULL),
  ('김재원', NULL),
  ('김재은', NULL),
  ('김정민', NULL),
  ('김정수', NULL),
  ('김정숙', NULL),
  ('김정영', NULL),
  ('김주연', NULL),
  ('김주희', NULL),
  ('김지선', NULL),
  ('김지은', NULL),
  ('김지현', NULL),
  ('김진구', NULL),
  ('김진만', NULL),
  ('김진희', NULL),
  ('김채완', NULL),
  ('김태형', NULL),
  ('김현우', NULL),
  ('김환일', NULL),
  ('나가이 히데미', NULL),
  ('나데즈다 테피', 'Nadezhda Teffi'),
  ('나수민', NULL),
  ('나이토 유코', 'Yuko Naito'),
  ('나탈리 사로트', 'Nathalie Sarraute'),
  ('노경식', NULL),
  ('노기 모에기', NULL),
  ('노여래', NULL),
  ('니컬러스 빌런', 'Nicolas Billon'),
  ('니콜라이 고골', NULL),
  ('니콜라이 바실리예비치 고골', NULL),
  ('니콜라이 예브레이노프', 'Nikolai Evreinov'),
  ('니콜로 마키아벨리', 'Niccolò Machiavelli'),
  ('닉 페인', NULL),
  ('닐 사이먼', 'Neil Simon'),
  ('다리오 포', 'Dario Fo'),
  ('다이애나 클라크', NULL),
  ('데니스 폰비진', 'Denis Fonvizin'),
  ('데아 로어', 'Dea Loher'),
  ('데이비드 월러스', NULL),
  ('데이비드 홀리웰', 'David Halliwell'),
  ('동이향', NULL),
  ('디온 부시코', 'Dion Boucicault'),
  ('라빈드라나드 타고르', NULL),
  ('라오서', 'Lao She'),
  ('래리 겔바트', 'Larry Gelbart'),
  ('레오노르 콩피노', 'Léonore Confino'),
  ('레오니트 안드레예프', 'Leonid Andreyev'),
  ('레프 톨스토이', 'Leo Tolstoy'),
  ('로렌 군더슨', NULL),
  ('로버트 그린', 'Robert Greene'),
  ('로제 비트라크', 'Roger Vitrac'),
  ('로페 데 베가', 'Lope de Vega'),
  ('롤란트 시멜페니히', 'Roland Schimmelpfennig'),
  ('루쉰', NULL),
  ('루이지 피란델로', 'Luigi Pirandello'),
  ('루쥔', NULL),
  ('루징뤄', 'Lu Jingluo'),
  ('루치안 블라가', 'Lucian Blaga'),
  ('류보미르 시모비치', 'Ljubomir Simović'),
  ('류수현', NULL),
  ('류전윈', NULL),
  ('류진윈', NULL),
  ('리서우청', NULL),
  ('리처드 셰리든', 'Richard Brinsley Sheridan'),
  ('린 노티지', NULL),
  ('마갈리 무젤', 'Magali Mougel'),
  ('마리보', 'Pierre de Marivaux'),
  ('마쓰이 슈', NULL),
  ('마에다 시로', 'Shiro Maeda'),
  ('마에카와 도모히로', NULL),
  ('마틴 맥도나', 'Martin McDonagh'),
  ('막스 프리슈', 'Max Frisch'),
  ('막심 고리키', 'Maxim Gorky'),
  ('멍징후이', NULL),
  ('메난드로스', NULL),
  ('모리스 마테를링크', 'Maurice Maeterlinck'),
  ('모스 하트', 'Moss Hart'),
  ('모이세스 코프먼', NULL),
  ('모토야 유키코', 'Yukiko Motoya'),
  ('몰리에르', 'Molière'),
  ('문승배', NULL),
  ('미겔 데 세르반테스', 'Miguel de Cervantes'),
  ('미상', NULL),
  ('미셸 마르크 부샤르', 'Michel Marc Bouchard'),
  ('미셸 트랑블레', 'Michel Tremblay'),
  ('미야모토 겐', 'Ken Miyamoto'),
  ('미요시 주로', 'Juro Miyoshi'),
  ('미하일 레르몬토프', 'Mikhail Lermontov'),
  ('미하일 불가코프', 'Mikhail Bulgakov'),
  ('민경수', NULL),
  ('박근형', NULL),
  ('박본', NULL),
  ('박상현', NULL),
  ('박성환', NULL),
  ('박세은', NULL),
  ('박소윤', NULL),
  ('박수진', NULL),
  ('박아영', NULL),
  ('박영호', NULL),
  ('박은영', NULL),
  ('박재서', NULL),
  ('박정현', NULL),
  ('박조열', NULL),
  ('박주영', NULL),
  ('박지선', NULL),
  ('박찬규', NULL),
  ('박춘근', NULL),
  ('박형준', NULL),
  ('박혜겸', NULL),
  ('박효선', NULL),
  ('발터 하젠클레버', 'Walter Hasenclever'),
  ('배삼식', NULL),
  ('배소현', NULL),
  ('배시현', NULL),
  ('배해률', NULL),
  ('백승연', NULL),
  ('백하룡', NULL),
  ('버트 셰브러브', 'Burt Shevelove'),
  ('베르나르 마리 콜테스', NULL),
  ('베르나르 베르베르', NULL),
  ('베르톨트 브레히트', 'Bertolt Brecht'),
  ('베쓰야쿠 미노루', 'Minoru Betsuyaku'),
  ('벤 존슨', 'Ben Jonson'),
  ('변경민', NULL),
  ('보마르셰', 'Beaumarchais'),
  ('볼테르', 'Voltaire'),
  ('브라이언 프리엘', 'Brian Friel'),
  ('블라디미르 루킨', 'Vladimir Lukin'),
  ('비톨트 곰브로비치', NULL),
  ('빅토르 아임', 'Victor Haïm'),
  ('빅토르 위고', 'Victor Hugo'),
  ('빅토리앵 사르두', 'Victorien Sardou'),
  ('빌 노턴', 'Bill Naughton'),
  ('사뮈엘 베케트', 'Samuel Beckett'),
  ('사예신', NULL),
  ('사이토 렌', NULL),
  ('사카모토 유지', NULL),
  ('상드린 로슈', 'Sandrine Roche'),
  ('샤옌', 'Xia Yan'),
  ('서민준', NULL),
  ('서유진', NULL),
  ('서철원', NULL),
  ('석예원', NULL),
  ('선명주', NULL),
  ('선욱현', NULL),
  ('선주태', NULL),
  ('설유진', NULL),
  ('성기웅', NULL),
  ('성원태', NULL),
  ('세라 룰', 'Sarah Ruhl'),
  ('세르지 벨벨', 'Sergi Belbel'),
  ('세르히오 블랑코', 'Sergio Blanco'),
  ('소윤정', NULL),
  ('소포클레스', 'Sophocles'),
  ('손성연', NULL),
  ('손턴 와일더', 'Thornton Wilder'),
  ('손희범', NULL),
  ('송미경', NULL),
  ('송민아', NULL),
  ('송영', NULL),
  ('송인헌', NULL),
  ('송천영', NULL),
  ('송희지', NULL),
  ('숀 오케이시', 'Sean O''Casey'),
  ('수전 글래스펠', 'Susan Glaspell'),
  ('쉬잉', NULL),
  ('쉬줘다이', 'Xu Zhuodai'),
  ('스류', NULL),
  ('스즈키 아쓰토', 'Atsuto Suzuki'),
  ('스타니스와프 이그나찌 비트키에비치', NULL),
  ('스테파노 마시니', 'Stefano Massini'),
  ('시도니 가브리엘 콜레트', NULL),
  ('시드니 마이클스', 'Sidney Michaels'),
  ('시바 유키오', NULL),
  ('신범수', NULL),
  ('신서영', NULL),
  ('신성우', NULL),
  ('신영은', NULL),
  ('신유진', NULL),
  ('신은수', NULL),
  ('신해연', NULL),
  ('신호권', NULL),
  ('신화영', NULL),
  ('신효진', NULL),
  ('쑹즈디', 'Song Zhidi'),
  ('쓰쿠다 노리히코', 'Norihiko Tsukuda'),
  ('아고타 크리스토프', NULL),
  ('아르느 리그르', 'Arne Lygre'),
  ('아르투어 슈니츨러', 'Arthur Schnitzler'),
  ('아리스토파네스', 'Aristophanes'),
  ('아리엘 도르프만', NULL),
  ('아서 밀러', 'Arthur Miller'),
  ('아우구스트 스트린드베리', 'August Strindberg'),
  ('아이스킬로스', 'Aeschylus'),
  ('안드레아스 그뤼피우스', 'Andreas Gryphius'),
  ('안정민', NULL),
  ('안토니오 부에로 바예호', 'Antonio Buero Vallejo'),
  ('안토니오 부예로 바예호', 'Antonio Buero Vallejo'),
  ('안톤 체호프', 'Anton Chekhov'),
  ('알간지', NULL),
  ('알레한드로 카소나', 'Alejandro Casona'),
  ('알렉산드르 블로크', 'Alexander Blok'),
  ('알렉산드르 세르게비치 푸시킨', NULL),
  ('알렉산드르 수마로코프', 'Alexander Sumarokov'),
  ('알렉산드르 푸시킨', 'Alexander Pushkin'),
  ('알렉상드르 뒤마 피스', 'Alexandre Dumas fils'),
  ('알베르 카뮈', NULL),
  ('알프레드 드 뮈세', 'Alfred de Musset'),
  ('알프레드 자리', 'Alfred Jarry'),
  ('애프러 벤', 'Aphra Behn'),
  ('앨런 버넷', NULL),
  ('야마모토 스구루', NULL),
  ('야스미나 레자', 'Yasmina Reza'),
  ('야오밍더', NULL),
  ('야오이웨이', 'Yao Yiwei'),
  ('야코프 렌츠', 'Jakob Michael Reinhold Lenz'),
  ('야코프 크냐지닌', 'Yakov Knyazhnin'),
  ('양샤오쉐', NULL),
  ('양수근', NULL),
  ('양정웅', NULL),
  ('양젠', NULL),
  ('어단비', NULL),
  ('어우양위첸', 'Ouyang Yuqian'),
  ('엄인희', NULL),
  ('에두아르도 드 필리포', 'Eduardo De Filippo'),
  ('에드몽 로스탕', 'Edmond Rostand'),
  ('에드몽 로스탕 (원작)', NULL),
  ('에드워드 올비', NULL),
  ('에르네스토 카바예로', 'Ernesto Caballero'),
  ('에른스트 톨러', 'Ernst Toller'),
  ('에우리피데스', 'Euripides'),
  ('엘리자베스 케리', 'Elizabeth Cary'),
  ('연혜원', NULL),
  ('예브게니 시바르츠', 'Evgeny Schwartz'),
  ('오가와 미레이', NULL),
  ('오노레 드 발자크', 'Honoré de Balzac'),
  ('오성호', NULL),
  ('오세혁', NULL),
  ('오스카 와일드', 'Oscar Wilde'),
  ('오예슬', NULL),
  ('오완', NULL),
  ('오종우', NULL),
  ('오진희', NULL),
  ('오태영', NULL),
  ('와즈디 무아와드', 'Wajdi Mouawad'),
  ('와타나베 에리', 'Eri Watanabe'),
  ('왕실보', 'Wang Shifu'),
  ('왕팅팅', NULL),
  ('외된 폰 호르바트', 'Ödön von Horváth'),
  ('외젠 라비슈', 'Eugène Labiche'),
  ('외젠 이오네스코', 'Eugène Ionesco'),
  ('요한 루트비히 티크', 'Johann Ludwig Tieck'),
  ('요한 볼프강 폰 괴테', 'Johann Wolfgangvon Goethe'),
  ('욘 포세', 'Jon Fosse'),
  ('우디 앨런', 'Woody Allen'),
  ('우종희', NULL),
  ('원팡이', NULL),
  ('월레 소잉카', 'Wole Soyinka'),
  ('웬디 케슬먼', 'Wendy Kesselman'),
  ('위기훈', NULL),
  ('윌리 러셀', 'Willy Russell'),
  ('윌리엄 셰익스피어', 'William Shakespeare'),
  ('유진 오닐', 'Eugene O''Neill'),
  ('유진월', NULL),
  ('유치진', NULL),
  ('유혜율', NULL),
  ('유희경', NULL),
  ('육지환', NULL),
  ('윤대성', NULL),
  ('윤미현', NULL),
  ('윤미희', NULL),
  ('윤성민', NULL),
  ('윤성호', NULL),
  ('윤소정', NULL),
  ('윤영률', NULL),
  ('윤영선', NULL),
  ('윤정준', NULL),
  ('윤정환', NULL),
  ('윤조병', NULL),
  ('윤주호', NULL),
  ('윤지영', NULL),
  ('이강백', NULL),
  ('이강호', NULL),
  ('이경헌', NULL),
  ('이그나시오 아메스토이', 'Ignacio Amestoy'),
  ('이근삼', NULL),
  ('이대현', NULL),
  ('이도경', NULL),
  ('이만희', NULL),
  ('이민규', NULL),
  ('이민선', NULL),
  ('이민호', NULL),
  ('이반 투르게네프', 'Ivan Turgenev'),
  ('이보람', NULL),
  ('이브 엔슬러', NULL),
  ('이상우', NULL),
  ('이서향', NULL),
  ('이선율', NULL),
  ('이선희', NULL),
  ('이소연', NULL),
  ('이송', NULL),
  ('이수진', NULL),
  ('이시원', NULL),
  ('이안재', NULL),
  ('이양구', NULL),
  ('이여진', NULL),
  ('이연주', NULL),
  ('이영은', NULL),
  ('이예본', NULL),
  ('이예찬', NULL),
  ('이오진', NULL),
  ('이온 루카 카라지알레', 'Ion Luca Caragiale'),
  ('이와사키 마사히로', NULL),
  ('이용찬', NULL),
  ('이용훈', NULL),
  ('이유진', NULL),
  ('이은샘', NULL),
  ('이은용', NULL),
  ('이익훈', NULL),
  ('이잠부', 'Li Qianfu'),
  ('이정', NULL),
  ('이철', NULL),
  ('이철희', NULL),
  ('이한주', NULL),
  ('이현화', NULL),
  ('이혜빈', NULL),
  ('이호영', NULL),
  ('이홍도', NULL),
  ('이홍주', NULL),
  ('임다은', NULL),
  ('임상미', NULL),
  ('임선규', NULL),
  ('임선영', NULL),
  ('임정은', NULL),
  ('임정자 원작', NULL),
  ('입과손스튜디오', NULL),
  ('자오야오민', NULL),
  ('장 라신', 'Jean Racine'),
  ('장 미셸 리브', 'Jean-Michel Ribes'),
  ('장 아누이', 'Jean Anouilh'),
  ('장 주네', 'Jean Genet'),
  ('장 지로두', 'Jean Giraudoux'),
  ('장 콕토', 'Jean Cocteau'),
  ('장 폴 사르트르', NULL),
  ('장-브누아 파트리코', 'Jean-Benoît Patricot'),
  ('장뤼크 라가르스', 'Jean-Luc Lagarce'),
  ('장성희', NULL),
  ('장아이링', NULL),
  ('장영', NULL),
  ('장우재', NULL),
  ('장웅식', NULL),
  ('장인영', NULL),
  ('장태준', NULL),
  ('장한나', NULL),
  ('장휘', NULL),
  ('전윤수', NULL),
  ('정미혜', NULL),
  ('정복근', NULL),
  ('정송연', NULL),
  ('정영욱', NULL),
  ('정우숙', NULL),
  ('정윤주', NULL),
  ('정의신', NULL),
  ('정준호', NULL),
  ('정진새', NULL),
  ('정창환', NULL),
  ('정현우', NULL),
  ('정희정', NULL),
  ('제여산', 'Qi Rushan'),
  ('조 오튼', 'Joe Orton'),
  ('조광화', NULL),
  ('조르주 페이도', 'Georges Feydeau'),
  ('조엘 폼므라', 'Joël Pommerat'),
  ('조은주', NULL),
  ('조인숙', NULL),
  ('조정일', NULL),
  ('조지 버나드 쇼', 'George Bernard Shaw'),
  ('조지 에이킨', 'George L. Aiken'),
  ('조지 코프먼', 'George S. Kaufman'),
  ('조태준', NULL),
  ('조한빈', NULL),
  ('존 릴리', 'John Lyly'),
  ('존 마스턴', 'John Marston'),
  ('존 매런스', 'Jon Marans'),
  ('존 밀링턴 싱', 'J. M. Synge'),
  ('존 바턴', 'John Barton'),
  ('존 오스번', 'John Osborne'),
  ('존 웹스터', 'John Webster'),
  ('존 퍼드', 'John Ford'),
  ('존 플레처', 'John Fletcher'),
  ('주샤오핑', NULL),
  ('주우진', NULL),
  ('주원규', NULL),
  ('주은길', NULL),
  ('주인석', NULL),
  ('주주', NULL),
  ('주효민', NULL),
  ('줄스 파이퍼', 'Jules Feiffer'),
  ('지은이 모름', NULL),
  ('진실', NULL),
  ('진주', NULL),
  ('쩡자오홍', 'Zeng Zhaohong'),
  ('차근호', NULL),
  ('차범석', NULL),
  ('차영아', NULL),
  ('차오위', NULL),
  ('차현석', NULL),
  ('창작집단 푸른수염', NULL),
  ('채만식', NULL),
  ('천바이천', 'Chen Baichen'),
  ('천스안', NULL),
  ('천쓰안', NULL),
  ('천정완', NULL),
  ('천쯔두', NULL),
  ('최기우', NULL),
  ('최보영', NULL),
  ('최원종', NULL),
  ('최은영', NULL),
  ('최치언', NULL),
  ('최현묵', NULL),
  ('최형우', NULL),
  ('추효지', NULL),
  ('카렐 차페크', NULL),
  ('카를 발렌틴', 'Karl Valentin'),
  ('카를 슈테른하임', 'Carl Sternheim'),
  ('카를로 골도니', 'Carlo Goldoni'),
  ('카릴 처칠', 'Caryl Churchill'),
  ('칼데론 데 라 바르카', 'Pedro Calderón de la Barca'),
  ('케네스 카벤더', 'Kenneth Cavander'),
  ('케라리노 산드로비치', NULL),
  ('콤 드 벨시즈', 'Côme de Bellescize'),
  ('쿠르트 괴츠', 'Curt Goetz'),
  ('크리스토퍼 말로', 'Christopher Marlowe'),
  ('클로딘 갈레아', 'Claudine Galea'),
  ('타데우시 슬라보지아네크', 'Tadeusz Słobodzianek'),
  ('탕크레트 도르스트', 'Tankred Dorst'),
  ('태기수', NULL),
  ('테네시 윌리암스', NULL),
  ('테런스 맥널리', 'Terrence McNally'),
  ('텍토닉 시어터 프로젝트', NULL),
  ('톈샤오웨이', NULL),
  ('토마스 베른하르트', 'Thomas Bernhard'),
  ('토머스 노턴', 'Thomas Norton'),
  ('토머스 데커', 'Thomas Dekker'),
  ('토머스 미들턴', 'Thomas Middleton'),
  ('토머스 미들턴·윌리엄 로울리', 'Thomas Middleton'),
  ('토머스 색빌', 'Thomas Sackville'),
  ('톰슨 하이웨이', 'Tomson Highway'),
  ('티르소 데 몰리나', 'Tirso de Molina'),
  ('티머시 핀들리', 'Timothy Findley'),
  ('티아구 호드리게스', NULL),
  ('티엔친신', NULL),
  ('파스칼 랑베르', 'Pascal Rambert'),
  ('파트리크 쥐스킨트', 'Patrick Suskind'),
  ('판쥔', NULL),
  ('팔로마 페드레로', 'Paloma Pedrero'),
  ('패트릭 해밀턴', NULL),
  ('페데리코 가르시아 로르카', 'Federico García Lorca'),
  ('페데리코 로르카', 'Federico García Lorca'),
  ('페르난도 아라발', 'Fernando Arrabal'),
  ('페터 바이스', 'Peter Weiss'),
  ('페터 투리니', 'Peter Turrini'),
  ('페터 한트케', NULL),
  ('폴커 브라운', 'Volker Braun'),
  ('프란츠 그릴파르처', 'Franz Grillparzer'),
  ('프란츠 베르펠', 'Franz Werfel'),
  ('프랑크 베데킨트', 'Frank Wedekind'),
  ('프랜시스 보몬트', 'Francis Beaumont'),
  ('프리드리히 뒤렌마트', NULL),
  ('프리드리히 실러', 'Friedrich Schiller'),
  ('프리드리히 폰 실러', NULL),
  ('프리드리히 헤벨', 'Friedrich Hebbel'),
  ('플로리앙 젤레르', 'Florian Zeller'),
  ('피에르 보마르셰', NULL),
  ('피에르 코르네유', 'Pierre Corneille'),
  ('피터 셰퍼', 'Peter Shaffer'),
  ('필립 칸 고탄다', 'Philip Kan Gotanda'),
  ('핑크 지저인 3호', 'Pink Chiteijin 3gou'),
  ('하이나어 키파르트', 'Heinar Kipphardt'),
  ('하이너 뮐러', 'Heiner Müller'),
  ('하인리히 폰 클라이스트', 'Heinrich von Kleist'),
  ('하타사와 세이고', 'Seigo Hatasawa'),
  ('하태희', NULL),
  ('한동엽', NULL),
  ('한민규', NULL),
  ('한송희', NULL),
  ('한일연극교류협의회', NULL),
  ('한진오', NULL),
  ('한태숙', NULL),
  ('한현주', NULL),
  ('함세덕', NULL),
  ('해서우', NULL),
  ('허규', NULL),
  ('허선혜', NULL),
  ('헨리크 입센', 'Henrik Ibsen'),
  ('호메로스', NULL),
  ('홍단비', NULL),
  ('홍수정', NULL),
  ('홍원기', NULL),
  ('황나영', NULL),
  ('황대현', NULL),
  ('황수아', NULL),
  ('황정은', NULL),
  ('후스', 'Jan Hus'),
  ('후안 마요르가', 'Juan Mayorga'),
  ('후지타 다카히로', NULL),
  ('후지타 덴', 'Den Fujita'),
  ('훙선', 'Hong Shen');